First attempt to add - buildpgANDplrInSRCcontrib == 'true' -ability

diff --git a/.github/workflows/buildPLR.yml b/.github/workflows/buildPLR.yml
--- a/.github/workflows/buildPLR.yml
+++ b/.github/workflows/buildPLR.yml
@@ -37,7 +37,7 @@ jobs:
             PG_SOURCE: 'D:\PGSOURCE'
             #
             # buildpgFromSRC: true
-            # buildpgFromSRCmethod: make
+            # buildpgFromSRCmethod: make/meson
             # xor
             buildpgANDplrInSRCcontrib: true
             #
@@ -1074,7 +1074,8 @@ jobs:
           Platform: ${{ env.Platform }}
           R_ARCH: ${{ env.R_ARCH }}
           rversion: ${{ env.rversion }}
-          PG_SOURCE: ${{ env.PG_SOURCE }} # different
+          PG_SOURCE: ${{ env.PG_SOURCE }} # different - full
+          PG_HOME: ${{ env.PG_HOME }}     # different - empty - and below - it is not used
           PGROOT2: ${{ env.PGROOT2 }}
         run: |
           echo "Windows non-msvc Meson PG and Meson PL/R Setup Compile and Meson Test"
@@ -1105,10 +1106,13 @@ jobs:
           echo "R_ARCH: ${R_ARCH}"
           echo "rversion: ${rversion}"
           echo "PG_SOURCE: ${PG_SOURCE}"
+          echo "PG_HOME: ${PG_HOME}"
           echo "PGROOT2: ${PGROOT2}"
 
           export WORKSPACE=$(pwd)
           echo "WORKSPACE ${WORKSPACE}"
+
+          #### BEGIN R SECTION ####
 
           #
           # Trying smartly and hard to find the R_HOME
@@ -1137,7 +1141,7 @@ jobs:
             # Environment Variable on Github Actions
             #
             # THIS DOES NOT EXTRACT
-            # Rscript . . . cat(Sys.getenv("R_HOME")
+            # Rscript . . . cat(Sys.getenv("R_HOME"))
 
             # Temporary workarounds
 
@@ -1258,6 +1262,245 @@ jobs:
             export PATH="${R_HOME}/bin${R_ARCH}:${PATH}"
           fi
 
+          #### END R SECTION ####
+
+          #### BEGIN PG_SOURCE AND PG_HOME SECTION ####
+
+          if [ ! "${PG_SOURCE}" == "notset" ] && [ ! "${PG_SOURCE}" == "" ]
+          then
+            export PG_SOURCE=$(cygpath "${PG_SOURCE}")
+            echo "cygpath PG_SOURCE: ${PG_SOURCE}"
+          fi
+
+          if [ ! "${PG_HOME}" == "notset" ] && [ ! "${PG_HOME}" == "" ]
+          then
+            export PG_HOME=$(cygpath "${PG_HOME}")
+            echo "cygpath PG_HOME: ${PG_HOME}"
+          fi
+
+          #### END PG_SOURCE AND PG_HOME SECTION ####
+
+          #### BEGIN PKGCONFIG SECTION ####
+
+          echo "PKG_CONFIG_PATH: ${PKG_CONFIG_PATH}"
+          echo "PKG_CONFIG_SYSTEM_INCLUDE_PATH: ${PKG_CONFIG_SYSTEM_INCLUDE_PATH}"
+          echo "PKG_CONFIG_SYSTEM_LIBRARY_PATH: ${PKG_CONFIG_SYSTEM_LIBRARY_PATH}"
+
+          # note "Cygwin" has "no defaults"
+          #
+          # note MSYS(mingw) UCRT uses MSYSTEM_PREFIX="/ucrt64" in place of "/usr"
+          # note MSYS(mingw) UCRT variable PKG_CONFIG_PATH at the tail also has "/ucrt64/share/pkgconfig"
+          #
+          # This case handles Cygwin.
+          if [ "${PKG_CONFIG_PATH}" == "" ];                then export PKG_CONFIG_PATH="/usr/lib/pkgconfig"; fi
+          if [ "${PKG_CONFIG_SYSTEM_INCLUDE_PATH}" == "" ]; then export PKG_CONFIG_SYSTEM_INCLUDE_PATH="/usr/include"; fi
+          if [ "${PKG_CONFIG_SYSTEM_LIBRARY_PATH}" == "" ]; then export PKG_CONFIG_SYSTEM_LIBRARY_PATH="/usr/lib"; fi
+
+          export PKG_CONFIG_PATH_ORIG=$(echo "${PKG_CONFIG_PATH}" |  grep -o '^[^:]*')
+          echo "PKG_CONFIG_PATH_ORIG: ${PKG_CONFIG_PATH}"
+
+          export PKG_CONFIG_SYSTEM_INCLUDE_PATH_ORIG=$(echo "${PKG_CONFIG_SYSTEM_INCLUDE_PATH}" |  grep -o '^[^:]*')
+          echo "PKG_CONFIG_SYSTEM_INCLUDE_PATH_ORIG: ${PKG_CONFIG_SYSTEM_INCLUDE_PATH_ORIG}"
+
+          # For MSYS(mingw) and R environment variable R_ARCH and Rlib.dll.a.
+          # Need ONE single leftmost headish important library path.
+          export PKG_CONFIG_SYSTEM_LIBRARY_PATH_ORIG=$(echo "${PKG_CONFIG_SYSTEM_LIBRARY_PATH}" |  grep -o '^[^:]*')
+          # MSYS2(mingw) environments
+          # e.g. UCRT
+          # export PKG_CONFIG_SYSTEM_LIBRARY_PATH_ORIG="/ucrt64/lib"
+          echo "PKG_CONFIG_SYSTEM_LIBRARY_PATH_ORIG: ${PKG_CONFIG_SYSTEM_LIBRARY_PATH_ORIG}"
+
+          echo "PKG_CONFIG_PATH: ${PKG_CONFIG_PATH}"
+          echo "PKG_CONFIG_SYSTEM_INCLUDE_PATH: ${PKG_CONFIG_SYSTEM_INCLUDE_PATH}"
+          echo "PKG_CONFIG_SYSTEM_LIBRARY_PATH: ${PKG_CONFIG_SYSTEM_LIBRARY_PATH}"
+
+          #### END PKGCONFIG SECTION ####
+
+          #### BEGIN MAKE R INTO A LIBRARY ####
+
+          # Make R into a library
+          if [ ! -d "${PKG_CONFIG_SYSTEM_LIBRARY_PATH_ORIG}/pkgconfig" ]
+          then
+            mkdir "${PKG_CONFIG_SYSTEM_LIBRARY_PATH_ORIG}/pkgconfig"
+          fi
+
+          if [ ! -f "${PKG_CONFIG_SYSTEM_LIBRARY_PATH_ORIG}/pkgconfig/libR.pc" ]
+          then
+            # Uses the provided template file "libR.pc"
+            # This template file is "based" off of the "R for Cygwin" file /lib/pkgconfig/libR.pc.
+            cat "libR.pc" | sed "s|R_HOME|${R_HOME}|" | sed "s|R_ARCH|${R_ARCH}|" | sed "s/rversion/${rversion}/" > "${PKG_CONFIG_SYSTEM_LIBRARY_PATH_ORIG}/pkgconfig/libR.pc"
+          fi
+
+          # Cygwin already has the file /usr/lib/R/lib/libR.dll.a
+          # MSYS2 (mingw) compilers require libR.dll.a.
+          # That file is created by ddltool program parameter "--output-lib".
+          #
+          # Note, Windows compilers (e.g. msvc) require R.lib.
+          # To create this file, instead of using the "dlltool" program, use the msvc "lib" program.
+          # Alternately, in the Windows "msvc" compiler case, just rename an archive dll.a to be a .lib,
+          # and that also works.
+          #
+          if [ ! -d "${PKG_CONFIG_SYSTEM_LIBRARY_PATH_ORIG}${R_ARCH}" ]
+          then
+            mkdir   "${PKG_CONFIG_SYSTEM_LIBRARY_PATH_ORIG}${R_ARCH}"
+          fi
+
+          # Create and Move, or, Copy, the R static library,
+          # to the target location - "${PKG_CONFIG_SYSTEM_LIBRARY_PATH_ORIG}${R_ARCH}/libR.dll.a"
+          if [ ! -f "${PKG_CONFIG_SYSTEM_LIBRARY_PATH_ORIG}${R_ARCH}/libR.dll.a" ]
+          then
+            #
+            # These should? be exclusive cases.
+            #
+            # Cygwin Repository R install case.
+            # Do I need to do this at all?
+            # If I am not given the R.dll, then THEY must provide the static library libR.dll.a.
+            if [ -f         "${PKG_CONFIG_SYSTEM_LIBRARY_PATH_ORIG}/R/lib/libR.dll.a" ]
+            then
+              pushd         "${PKG_CONFIG_SYSTEM_LIBRARY_PATH_ORIG}/R/lib"
+              cp libR.dll.a "${PKG_CONFIG_SYSTEM_LIBRARY_PATH_ORIG}${R_ARCH}/libR.dll.a"
+              popd # from   "${PKG_CONFIG_SYSTEM_LIBRARY_PATH_ORIG}/R/lib"
+            fi
+            # Msys case using "R for Windows" from CRAN
+            # If I am given the R.dll, then I can myself, create the static library libR.dll.a.
+            if [ -f "${R_HOME}/bin${R_ARCH}/R.dll" ]
+            then
+              pushd "${R_HOME}/bin${R_ARCH}"
+              gendef  -         R.dll >     R.def
+              dlltool --dllname R.dll --def R.def --output-lib libR.dll.a
+              #
+              # Put libR.dll.a into the general library location {...ORIG}${R_ARCH}/libR.dll.a
+              mv libR.dll.a "${PKG_CONFIG_SYSTEM_LIBRARY_PATH_ORIG}${R_ARCH}/libR.dll.a"
+              popd # from "${R_HOME}/bin${R_ARCH}"
+            fi
+          fi
+
+          #### END MAKE R INTO A LIBRARY ####
+
+          #### BEGIN SETUP MESON.BUILD FILES AND OPTIONS ####
+
+          cat _meson_options.txt_postgres_root_additional_plr_option.txt >>         ${PG_SOURCE}/meson.build
+          echo 'subdir('"'"'plr'"'"')'                                   >> ${PG_SOURCE}/contrib/meson.build
+
+          mv  meson.build meson.build.STANDALONE.HIDDEN
+          mv _meson.build meson.build
+
+          #### END SETUP MESON.BUILD FILES AND OPTIONS ####
+
+          #### BEGIN CREATE THE PLR DIRECTORY ####
+
+          # Create the contrib/plr directory parallel in contrib.
+          # Copy all of the PL/R source code into contrib/plr.
+          #
+          mkdir     "${PG_SOURCE}/contrib/plr"
+          cp -R   * "${PG_SOURCE}/contrib/plr"
+
+          #### END CREATE THE PLR DIRECTORY ####
+
+          #### BEGIN BUILD PG AND PLR AND TEST PLR ####
+
+          pushd "${PG_SOURCE}"
+
+          meson setup --prefix "${PG_HOME}" -DR_HOME=${R_HOME} -Dbuildtype=release -Db_pie=true -Dnls=disabled -Dplperl=disabled -Dplpython=disabled -Dpltcl=disabled -Dicu=disabled -Dllvm=disabled -Dlz4=disabled -Dzstd=disabled -Dgssapi=disabled -Dldap=disabled -Dpam=disabled -Dbsd_auth=disabled -Dsystemd=disabled -Dbonjour=disabled -Dlibxml=disabled -Dlibxslt=disabled -Dreadline=enabled -Dzlib=disabled -Ddocs=disabled -Ddocs_pdf=disabled -Dcassert=false -Dtap_tests=disabled -Db_coverage=false -Ddtrace=disabled build
+
+          meson compile -C build -v
+
+          if [ "${OperatingSystem}" == "Cygwin" ]
+          then
+            echo "cygrunsrv START"
+            # shutdown current
+            #### cygrunsrv -E cygserver || true
+            # uninstall previous
+            #### cygrunsrv -R cygserver || true
+            # install
+            cygserver-config --yes
+            # postgresql failing with below error on lion os x
+            # https://stackoverflow.com/questions/6861945/postgresql-failing-with-below-error-on-lion-os-x#:~:text=Failed%20system%20call%20was%20shmget,the%20kernel%20with%20larger%20SHMMAX.
+            echo kern.ipc.shmall 4096 >>     /etc/defaults/etc/cygserver.conf
+            echo kern.ipc.shmmax 16777216 >> /etc/defaults/etc/cygserver.conf
+
+            # start
+            cygrunsrv -S cygserver
+          fi
+
+          meson test -C build --num-processes 1 -v --suite setup --suite plr
+
+          if [ "${OperatingSystem}" == "Cygwin" ]
+          then
+            echo "cygrunsrv STOP"
+            # shutdown current
+            cygrunsrv -E cygserver
+            # uninstall previous
+            #### cygrunsrv -R cygserver
+          fi
+
+          # save GOOD artifact plr.dll
+          #
+          if [ -f "build/contrib/plr/plr.dll" ]
+          then
+            echo "Save plr.dll to be an artifact."
+            mkdir -p                                ${WORKSPACE}/tmp/lib
+            cp    LICENSE                           ${WORKSPACE}/tmp/PLR_LICENSE
+            cp    "build/contrib/plr/plr.dll"       ${WORKSPACE}/tmp/lib
+            ls -alrt                                ${WORKSPACE}/tmp/lib/plr.dll
+            mkdir -p                                ${WORKSPACE}/tmp/share/extension
+            cp    *.control                         ${WORKSPACE}/tmp/share/extension
+            cp    *.sql                             ${WORKSPACE}/tmp/share/extension
+          fi
+
+          #
+          # save GOOD artifact plr.dll.a
+          #
+          if [ -f "build/contrib/plr/plr.dll.a" ]
+          then
+            echo "Save plr.dll.a to be an artifact."
+            mkdir -p                                  ${WORKSPACE}/tmp/lib
+            cp    "build/contrib/plr/plr.dll.a"       ${WORKSPACE}/tmp/lib
+            ls -alrt                                  ${WORKSPACE}/tmp/lib/plr.dll.a
+          fi
+
+          # 7z GOOD PL/R Artifact for LATER Release
+          echo "7z: $(which 7z)"
+          echo 7z a -r ${WORKSPACE}/plr-artifact.zip  ${WORKSPACE}/tmp/*
+          if [ -f "${WORKSPACE}/tmp/PLR_LICENSE" ]
+          then
+            echo "Create PL/R Artifact .zip for future Release"
+            7z a -r ${WORKSPACE}/plr-artifact.zip  ${WORKSPACE}/tmp/*
+          fi
+
+          export pgversion=$(./build/src/bin/pg_config | grep "^VERSION" | sed "s/ = /=/" | sed "s/^.*=//" | grep -oP '[ ].*$' | grep -oP '\d.*$')
+          # potential override
+          echo "pgversion=${pgversion}" >> ${GITHUB_ENV}
+          echo "pg_config VERSION pgversion: ${pgversion}"
+
+          popd # from ${PG_SOURCE}"
+
+          #### END BUILD PG AND PLR AND TEST PLR ####
+
+          # if "PostgreSQL for Windows" exists, then
+          # copy "Msys artifacts into "PostgreSQL for Windows" for future testing if env.MSYS2testonpgWIN == 'true'.
+          #
+          if ( [ ! "${PGROOT2}" == "notset" ] && [ ! "${PGROOT2}" == "" ] ) && [ "${OperatingSystem}" == "Msys" ]
+          then
+            export PGROOT2=$(cygpath "${PGROOT2}")
+            echo  "cygpath PGROOT2: ${PGROOT2}"
+
+            if [ -d "${PGROOT2}" ]
+            then
+              if [ -f "${PG_SOURCE}/build/contrib/plr/plr.dll" ]
+              then
+                echo "PGROOT2 is found. Preparing PostgreSQL for Windows testing."
+
+                cp  "${PG_SOURCE}/build/contrib/plr/plr.dll"   "${PGROOT2}/lib"
+                ls -alrt                                       "${PGROOT2}/lib/plr.dll"
+                cp plr.control                                 "${PGROOT2}/share/extension"
+                ls -alrt                                       "${PGROOT2}/share/extension/plr.control"
+                cp plr--*.sql                                  "${PGROOT2}/share/extension"
+                ls -alrt                                       "${PGROOT2}"/share/extension/plr--*.sql
+
+              fi
+            fi
+          fi
 
       - name: Windows non-msvc Meson PL/R Setup Compile and Non-Meson Manual Test
         if: ${{ env.os == 'windows-latest' && ( env.compilerClass == 'MSYS2' || env.compilerClass == 'cygwin' ) && env.buildpgANDplrInSRCcontrib != 'true' }}
@@ -1333,7 +1576,7 @@ jobs:
             # Environment Variable on Github Actions
             #
             # THIS DOES NOT EXTRACT
-            # Rscript . . . cat(Sys.getenv("R_HOME")
+            # Rscript . . . cat(Sys.getenv("R_HOME"))
 
             # Temporary workarounds
 
